### ISSUE TITLE
how to use 

### ISSUE THREAD

**Issue by furjac** [CarldricGaming/Mini-Compressor#1]
plz help how to use this to compress files

**Comment by CarldricGaming** [comment]
Grab a latest version of Mini Compressor, extract and use it.

For a first time to use, Browse the source (mostly you want to repack your games), Choose the output where you want to put it. Example: "C:\". Choose your method, mostly recommended "mcx". Then start to compress until you finished. If you failed to compress, save the result, and upload here (mostly people just copy and paste from text file).

**Comment by furjac** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/81816200/140628239-459a9fce-7ecf-4332-94b7-7161b89659a9.png)
im unable to open any file this is the problem

**Comment by CarldricGaming** [comment]
You just download a souce code. Here the release of Mini Compressor. Thanks for issue of source.

**Comment by furjac** [comment]
very very thanx man

**Comment by CarldricGaming** [comment]
No problem.

**Comment by furjac** [comment]
![Capture](https://user-images.githubusercontent.com/81816200/142731944-7e804ea4-8c2d-475a-b12a-a5a87e309613.PNG)
bro how to add my bin file to extract
