### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by Yarpopcat08** [CarldricGaming/Mini-Compressor#10]
So,  after compiling the Inno Maker setup and running it, it gives this error
![error extraction thingy](https://user-images.githubusercontent.com/109970976/204818901-3548983f-5fe9-45a9-89a1-23e2e24f5765.png)
I found this **ISDone.dll** in the files of the Mini-Compressor, put it in the directory with the installer, nothing changed.

Please help me if you can...

**Comment by CarldricGaming** [comment]
It looks like you did something wrong... Please give me a full details that you use on Inno Maker... But don't compile it first. Save a project and send your project here

**Comment by CarldricGaming** [comment]
Here's the latest version of **Mini Compressor**.
[v21.7h](https://github.com/CarldricGaming/Mini-Compressor/releases/tag/v21.7h)

**Comment by Yarpopcat08** [comment]
Oh, thank you so much! It works now!

**Comment by CarldricGaming** [comment]
> Oh, thank you so much! It works now!

You always welcome.
