### ISSUE TITLE
Not stable on Windows 7

### ISSUE THREAD

**Issue by vadimlitvinenko87** [CarldricGaming/Mini-Compressor#11]
[v21.8i - Stable](https://github.com/CarldricGaming/Mini-Compressor/releases/tag/v21.8i) IT IS NOT STABLE.
Not work in 7 and 10 windows.

P.S. Looks like AV delete xhash
Anyway not work on windows 7

**Comment by vadimlitvinenko87** [comment]
В России таких зовут РУКОЖОП

**Comment by CarldricGaming** [comment]
On my way to solution

**Comment by CarldricGaming** [comment]
I did found nothing that you say **Not stable on Windows 7 and Windows 10**.

Here's the photo was work fine.

![Win10_x64](https://user-images.githubusercontent.com/46277745/213845100-6ddf42a8-c6bb-4ecb-8381-bb44844e1b68.jpg)

![Win7_x64](https://user-images.githubusercontent.com/46277745/213845096-9c1c452d-906f-4449-a25d-b30cbb2ae64a.png)

**Comment by CarldricGaming** [comment]
Since you didn't respond, I closed the thread because you didn't respond.
