### ISSUE TITLE
Virus Detection on latest release

### ISSUE THREAD

**Issue by FayeReagan** [CarldricGaming/Mini-Compressor#12]
Hi, is this false positive? I can't exclude XHashNext.dll manually from my AV
https://www.virustotal.com/gui/file/5555b647c2753dc038596d2e60e82f5089897a36f68eb1fbdad7b7434669ce71

**Comment by CarldricGaming** [comment]
It was false. Just do disable AV and exclude folder **Mini Compressor** only.
XHashNext.dll uses to generate MD5 file games/etc.

**Comment by FayeReagan** [comment]
Thanks for confirming it, have a nice day
