### ISSUE TITLE
Launcher.exe triggered malware as false positive 

### ISSUE THREAD

**Issue by alexmannen** [CarldricGaming/Mini-Compressor#14]
why are 18 av on virustotal flagging launcher as malware?

**Comment by CarldricGaming** [comment]
It was packed with UPX and it will triggered as false positive... Will fix it soon.

**Comment by CarldricGaming** [comment]
[Launcher_Fixed.zip](https://github.com/CarldricGaming/Mini-Compressor/files/11239996/Launcher_Fixed.zip)

Here's the launcher fixed.
