### ISSUE TITLE
Compression failed

### ISSUE THREAD

**Issue by furjac** [CarldricGaming/Mini-Compressor#16]
i Started compressing a 23Gb file at 15% it says compression failed i tried to save report but it was empty dono why it showed additional two popups one was the directory is not empty and other was out of memory and a specified error was the blahblah.png is not accessible dono whats the actual error plz help ill also post screenshot soon i used method -mpcx i also enabled use protect
![Screenshot (8)](https://user-images.githubusercontent.com/81816200/234757196-3eb02411-0a0c-496a-bd00-184ea79cc1aa.png)

**Comment by CarldricGaming** [comment]
Can you give details about the file? It might be the case problem of mp3 file or something... If it was, try custom method to do so and try compress without arc protection mode.

**Comment by furjac** [comment]
so these were the errors
![Screenshot (9)](https://user-images.githubusercontent.com/81816200/234819769-81c1c9e0-2c57-46ba-8b36-fc2b92108018.png)
![Screenshot (10)](https://user-images.githubusercontent.com/81816200/234819779-f88a2841-7073-4992-bf8b-51eb9dcccab3.png)
![Screenshot (11)](https://user-images.githubusercontent.com/81816200/234819785-169994a9-244e-42b0-8808-52c3418b3bdd.png)

**Comment by furjac** [comment]
so the software is much bigger dono what files they are maybe ill check it later

**Comment by CarldricGaming** [comment]
Try to disable antivirus. If was not work, will check the code was compromised...

**Comment by furjac** [comment]
And bro I completely disabled anti-virus from first only I don't like them

**Comment by CarldricGaming** [comment]
That's weird...

![image](https://user-images.githubusercontent.com/46277745/234888595-74fe6167-bc5a-49af-9278-6ca9db2b6226.png)

When I'm trying to close it seems to be fine here though...
![image](https://user-images.githubusercontent.com/46277745/234888757-7170a6ca-9f76-4f34-9858-9aecee1fc77b.png)

**Comment by furjac** [comment]
![Screenshot_20230427-202541_Discord.jpg](https://user-images.githubusercontent.com/81816200/234902442-a9e064c0-7340-4231-9795-ee7b914cec09.jpg)

**Comment by furjac** [comment]
https://discord.gg/YN9RKxewsq
Use thus instead
