### ISSUE TITLE
Mini Compressor  Self-Extracting doesn't work.

### ISSUE THREAD

**Issue by GustavRaispits** [CarldricGaming/Mini-Compressor#17]
The tool is amazing but it got one big issue, when I click "Extract" inside the Self-Extracting tool it remains stuck like that:

![image](https://github.com/CarldricGaming/Mini-Compressor/assets/34628862/f7138efa-cf3c-4a9b-a514-3f878fb9d147)

What is the cause of that?

**Comment by CarldricGaming** [comment]
Would check again sfx if the code was compromised again...

**Comment by GustavRaispits** [comment]
> Would check again sfx if the code was compromised again...

I'm new to that, what do you mean by compromised?

**Comment by CarldricGaming** [comment]
> > Would check again sfx if the code was compromised again...
> 
> I'm new to that, what do you mean by compromised?

Simple answer, if it was sfx problem, there is something problem couldn't be finish yet or else.

**Comment by GustavRaispits** [comment]
> > > Would check again sfx if the code was compromised again...
> > 
> > 
> > I'm new to that, what do you mean by compromised?
> 
> Simple answer, if it was sfx problem, there is something problem couldn't be finish yet or else.

Thank you for paying attention to my report, I've tried again the optimized SFX released on v22.0 but looks like the problem is still here, I've encountered the "out of memory" problem caused by a PNG while compressing a really big file.

Good luck fixing the issues!

**Comment by CarldricGaming** [comment]
Can you give me a details about you're using OS?

And any antivirus have you disabled before? If it was try to disable first...

And last if you get message "Out of memory" was failed about PNG, try to change Skin.

**Comment by GustavRaispits** [comment]
> Can you give me a details about you're using OS?
> 
> And any antivirus have you disabled before? If it wasn't try to disable first that could cause SFX problem.
> 
> And last if you get message "Out of memory" was failed about PNG, try to change Skin.

At the time I used your program I was using Windows 11 PRO build 22621.1702, when I was using the program no antivirus was running [I've even forcefully uninstalled Windows Defender], for some reason the SFX appears to get stuck once I start it. I'll try the SFX again during the next days if I'll not be busy.

**Comment by GustavRaispits** [comment]
> Can you give me a details about you're using OS?
> 
> And any antivirus have you disabled before? If it wasn't try to disable first that could cause SFX problem.
> 
> And last if you get message "Out of memory" was failed about PNG, try to change Skin.

I've tried to change the skin and wallpaper of my program, but this problem still occurs when compressing big folders with certain compression algorithms:

![arAdiM2](https://github.com/CarldricGaming/Mini-Compressor/assets/34628862/5a5eec1f-bfe9-45e2-8993-1b006f7dbc36)

![a9Bpqii](https://github.com/CarldricGaming/Mini-Compressor/assets/34628862/4441761b-5eec-435f-a740-b83faee849c6)

Wallpaper used:

![OVsvrud](https://github.com/CarldricGaming/Mini-Compressor/assets/34628862/830045b5-3ab9-413b-983b-5b2f93c1d768)

Programs running in background:

![wSOMgi9](https://github.com/CarldricGaming/Mini-Compressor/assets/34628862/706b86b7-9c18-4964-b22c-529f6d24780f)

OS Build and specs:

![CNQiqOP](https://github.com/CarldricGaming/Mini-Compressor/assets/34628862/aedeb32f-b926-4289-a89a-0c0fc204f762)

Demo showing various issues of SFX:

1st try:

https://github.com/CarldricGaming/Mini-Compressor/assets/34628862/a027c3d9-1fc8-4fb3-9d11-004b3e84be62

Sometimes the SFX creation doesn't fail during the first run when compressing lighter folders.

2nd try:

When I tried to compress the same exact file with the same exact settings as shown as on the first try, this happened:

![iNgI3lR](https://github.com/CarldricGaming/Mini-Compressor/assets/34628862/be0a19eb-270b-4d67-b7c6-a43e867b17da)

When I try to close the program through the taskbar this error keeps popping up, forcing me to use the task manager for terminating the process, this error occurs especially after using Mini Compressor multiple times during one session.

3rd try with a different and lighter folder:

https://github.com/CarldricGaming/Mini-Compressor/assets/34628862/81978a45-03f1-4d5b-a7b3-ef2d7bc06128

Good luck fixing every issue! If you need more information and help feel free to ask.

**Comment by CarldricGaming** [comment]
Here's the latest version.
[v22.1](https://github.com/CarldricGaming/Mini-Compressor/releases/tag/v22.1)
