### ISSUE TITLE
Bug Issue of "Compiler of Inno Maker didn't updated"

### ISSUE THREAD

**Issue by Cod3xDev** [CarldricGaming/Mini-Compressor#19]
MC_v22.0-Stable works perfectly for me. However, 22.1 doesn't for me unfortunately, I've tested several games and it's all the same error.

<img width="960" alt="Untitled" src="https://github.com/CarldricGaming/Mini-Compressor/assets/67140619/71ff1c22-cb93-4964-9aeb-6bd8293ccfc7">

any help would be appreciated

**Comment by CarldricGaming** [comment]
Is that Inno Maker or Installer Creator?

**Comment by Cod3xDev** [comment]
I'm not sure I finish work at 3:30 PM GMT+10. I'll check then I managed to use 22.1 to make the arc then 22.0 for the installer. I will provide the steps I used and also my save/load for the setup I used. 

Also thank you so much for this tool ❤️

**Comment by CarldricGaming** [comment]
Please do check if any was a bug... thanks.

**Comment by Cod3xDev** [comment]
Used Inno Maker it compiles the exe but still says missing setup.db
+ Uploaded test.imp I used as an example in the Test.zip
[Test.zip](https://github.com/CarldricGaming/Mini-Compressor/files/12582846/Test.zip)

![Screenshot 2023-09-12 155353](https://github.com/CarldricGaming/Mini-Compressor/assets/67140619/379c8845-9ef3-463e-8cce-48488d126153)

**Comment by CarldricGaming** [comment]
[Compiler - Patch 1.zip](https://github.com/CarldricGaming/Mini-Compressor/files/12583293/Compiler.-.Patch.1.zip)

Just replace the Compiler on Installer Folder.

**Comment by CarldricGaming** [comment]
If you have any problem's, then it's decided to close this thread. Thanks
