### ISSUE TITLE
How to add source file to output dir

### ISSUE THREAD

**Issue by CarldricGaming** [CarldricGaming/Mini-Compressor#2]
![Capture](https://user-images.githubusercontent.com/81816200/142731944-7e804ea4-8c2d-475a-b12a-a5a87e309613.PNG)
bro how to add my bin file to extract

_Originally posted by @furjac in https://github.com/CarldricGaming/Mini-Compressor/issues/1#issuecomment-974665816_

**Comment by CarldricGaming** [comment]
Adding your files, just edit the memo like notepad. No need to confused. Example

[Archive1]
Type=Freearc
Source={src}\Setup-1.bin
Output={app}
Disk=1
Password=yourpassword

[Archive2]
Type=7Zip
Source={src}\Data1.7z
Output={app}
Disk=2
Password=yourpassword

If you didn't put the password your file, blank it and add again by pressing the Add button.

**Comment by furjac** [comment]
its saying outputdir error

**Comment by furjac** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/81816200/142751637-06989a2b-b1b1-4e35-a77b-48b20818ee00.png)

**Comment by furjac** [comment]
no this solved plz close this issue in last tab i didn't specify output sorry
And a big thanx for this software.Thanx

**Comment by CarldricGaming** [comment]
> no this solved plz close this issue in last tab i didn't specify output sorry And a big thanx for this software.Thanx

It's ok dude. As long as you needed. 😃
