### ISSUE TITLE
Bug Issue of Mini-Compressor When Repacking

### ISSUE THREAD

**Issue by Cod3xDev** [CarldricGaming/Mini-Compressor#20]
I'd say roughly 50% of the time when repacking I get the following errors

![Screenshot 2023-09-25 145337](https://github.com/CarldricGaming/Mini-Compressor/assets/67140619/15bd27f6-9a2e-4df7-a5af-93d8c8a8e7d6)

![Screenshot 2023-09-25 145344](https://github.com/CarldricGaming/Mini-Compressor/assets/67140619/d20b4a33-9d9c-4d27-9b8a-281f7d8f4523)

Upon closing the program I get the following error

![Screenshot 2023-09-25 145838](https://github.com/CarldricGaming/Mini-Compressor/assets/67140619/67d0158f-4996-4586-b5ce-2e95d8620510)

**Comment by CarldricGaming** [comment]
Would check it soon if there was any compromise again.

**Comment by Cod3xDev** [comment]
Something must've corrupted, Re-Downloaded latest version, Re-Applied Compilere.exe (Fix), fixed issue also used RUN (CMD) instead of Start

**Comment by Cod3xDev** [comment]
+1 Issue Seems To Still Be Present

**Comment by furjac** [comment]
So yes this issue is true it only gives this error when i try to compress a software not games if games it will not give this error

**Comment by CarldricGaming** [comment]
use the split option. Also, there's a new update v2023.10.22 right now.
[Here](https://github.com/CarldricGaming/Mini-Compressor/releases/tag/v2023.10.22)
