### ISSUE TITLE
XTool stuck from pre-processing files from any type of games.

### ISSUE THREAD

**Issue by NonVolatileHuman** [CarldricGaming/Mini-Compressor#22]
![Screenshot (5)](https://github.com/CarldricGaming/Mini-Compressor/assets/75540320/88fe4068-4f27-4301-bab2-bfeb6f88382e)
I'm using the latest 23.10 version on the latest Win11 Pro build, I only checked to make an SFX and MD5 and used the MSX method on the "Original" tab. I have no idea what happens and when I try to close the launcher it says "Out of memory" and stays in the task manager until I End the Task from there, I have 16GB of RAM.

**Comment by NonVolatileHuman** [comment]
![Uploading Screenshot (5).png…]()

**Comment by CarldricGaming** [comment]
Use the latest version Mini Compressor.

**Comment by NonVolatileHuman** [comment]
I don't understand, does that mean that I should check the lolz compression or that you will check it?
I checked three times with lolz and the same issue happened. I'm currently using normal FreeArc with no problem on version 0.67alpha.

**Comment by Cod3xDev** [comment]
+1 Same Issue, Also I Can't seem to get Run (CMD) to work, It's like the cmd tries to open up but closes instantly then gives an error;

![Screenshot 2023-11-04 081901](https://github.com/CarldricGaming/Mini-Compressor/assets/67140619/1b4bce67-0521-4bf2-be5b-8c6d1c1ca9fb)

**Comment by NonVolatileHuman** [comment]
Yes! Same here too!

**Comment by Cod3xDev** [comment]
Seems the new Windows 11 Update 23H2 might have something to do with the Run (CMD) option not popping up, just a thought.

**Comment by CarldricGaming** [comment]
Will check ASAP now.

**Comment by CarldricGaming** [comment]
I did manage some XTool that didn't respond and got pre-processed some games. and now it works.

![image](https://github.com/CarldricGaming/Mini-Compressor/assets/46277745/fe310b83-f600-4f89-b4f0-3e9e168b15d5)

Also the CMD, the latest version of Windows 11 23H2 might have the wrong position of cmd. I need to configure it anyway.

![image](https://github.com/CarldricGaming/Mini-Compressor/assets/46277745/6ab1bfd8-ce6c-4ec2-a6ee-3f5ca16f93b1)

**Comment by Cod3xDev** [comment]
That worked! I'm so used to running everything as Administrator. Thank you kindly! <3

**Comment by CarldricGaming** [comment]
Latest version is released. [Here](https://github.com/CarldricGaming/Mini-Compressor/releases/tag/v2023.11.6)

**Comment by NonVolatileHuman** [comment]
I just checked and the compression works fine with pre-comp, but I found an issue with SFX extraction.

**Comment by CarldricGaming** [comment]
> ![Screenshot (5)](https://user-images.githubusercontent.com/75540320/279958094-88fe4068-4f27-4301-bab2-bfeb6f88382e.png) I'm using the latest 23.10 version on the latest Win11 Pro build, I only checked to make an SFX and MD5 and used the MSX method on the "Original" tab. I have no idea what happens and when I try to close the launcher it says "Out of memory" and stays in the task manager until I End the Task from there, I have 16GB of RAM.

After finally fixing the issue of TMemo causing issues Out of memory, Mini Compressor will become stable now.

![VidZ 2023-11-11 21-38-42-650](https://github.com/CarldricGaming/Mini-Compressor/assets/46277745/a42be8ef-7bd8-4842-8130-f1b8010ebf94)

**Comment by CarldricGaming** [comment]
The latest has been released. [Here](https://github.com/CarldricGaming/Mini-Compressor/releases/tag/v2023.11.12)
