### ISSUE TITLE
Outdated skin from Delphi XE10

### ISSUE THREAD

**Issue by rreha** [CarldricGaming/Mini-Compressor#23]
### Using the _**v2023.10.22 - Stable**_ release

Changing to **"Blend"**, **"Amakrits"**, **"GoldenGraphite"** and **"RubyGraphite"** gives this error first:
![image](https://github.com/CarldricGaming/Mini-Compressor/assets/74599574/86512ec5-b332-49d2-9e08-1a319e4343ed)

Then when you relaunch the program, gives this error:
![image](https://github.com/CarldricGaming/Mini-Compressor/assets/74599574/b31d24c5-fc4f-49e8-a2cd-f76f7329472b)

**"Jet"**, "**Transparent"**, **"Beta"** skins works fine.

**Comment by CarldricGaming** [comment]
will update the skin asap.

**Comment by CarldricGaming** [comment]
Hopefully it work for you. [Here](https://github.com/CarldricGaming/Mini-Compressor/releases/tag/v2023.11.6)

**Comment by rreha** [comment]
The issue got solved, thank you!
