### ISSUE TITLE
SFX didn't update after release v2023.11.6

### ISSUE THREAD

**Issue by NonVolatileHuman** [CarldricGaming/Mini-Compressor#24]
**_I have uploaded a screenshot of the final error and all the steps I took to recreate it. The folder being compressed has only PDFs inside, no complicated files/formats/extensions._**

![Screenshot (8)](https://github.com/CarldricGaming/Mini-Compressor/assets/75540320/67bf93f8-f6e4-4825-b581-a22ef6ebfb19)

https://github.com/CarldricGaming/Mini-Compressor/assets/75540320/c4884e0b-ea8a-461b-85d0-2f41cdbd7f41

![Screenshot (11)](https://github.com/CarldricGaming/Mini-Compressor/assets/75540320/0faa3b29-566c-42ba-aaa1-689f4e08b05b)
(Specs)

**Comment by CarldricGaming** [comment]
hotfix 1 is released. [Here](https://github.com/CarldricGaming/Mini-Compressor/releases/tag/v2023.11.6-Hotfix-1)

**Comment by NonVolatileHuman** [comment]
Awesome work, Carldric! SFX works fine now.
