### ISSUE TITLE
Recovery record to prevent archive corruption.

### ISSUE THREAD

**Issue by NonVolatileHuman** [CarldricGaming/Mini-Compressor#25]
Is there a way to add a recovery record to prevent archives from being corrupted during transport/download the same way vanilla FreeArc allows you to make one?

![Screenshot (12)](https://github.com/CarldricGaming/Mini-Compressor/assets/75540320/6581d262-b8a3-4278-844c-698eb12e11a3)
![Screenshot (13)](https://github.com/CarldricGaming/Mini-Compressor/assets/75540320/5b4c8c1b-5e0a-4bf0-bab4-29f5d74edd85)

**Comment by CarldricGaming** [comment]
> Is there a way to add a recovery record to prevent archives from being corrupted during transport/download the same way vanilla FreeArc allows you to make one?
> 
> ![Screenshot (12)](https://user-images.githubusercontent.com/75540320/281004926-6581d262-b8a3-4278-844c-698eb12e11a3.png) ![Screenshot (13)](https://user-images.githubusercontent.com/75540320/281004940-5b4c8c1b-5e0a-4bf0-bab4-29f5d74edd85.png)

I'm not sure what command option to use protection. But you can customize on Compression\FreeArc_Cmd.ini

**Comment by NonVolatileHuman** [comment]
> Compression\FreeArc_Cmd.ini

This file doesn't exist, I searched the whole Mini Compressor directory.

**Comment by CarldricGaming** [comment]
ahh, I see...

![image](https://github.com/CarldricGaming/Mini-Compressor/assets/46277745/76aaf43c-8309-403d-b5ea-4439943c3c97)

don't know how to use though... so basically you want to add this protection for your archive?

![image](https://github.com/CarldricGaming/Mini-Compressor/assets/46277745/71f4823f-78f8-4045-9ddd-6c7023569e8d)

**Comment by NonVolatileHuman** [comment]
That's Awesome!!
but is 5% supposed to translate into 1 sector (256 Kbytes)?
Did you try higher percentages and see if the sector number changes?

**Comment by CarldricGaming** [comment]
> That's Awesome!! But is 5% supposed to translate into 1 sector (256 kbytes)? Did you try higher percentages and see if the sector number changes?
> 
> Testing this in the field would involve you making an archive, then intentionally corrupting it then seeing if the repair function kicks in.

I didn't have try higher percentage before since that I use FreeARC Protect that wouldn't let someone steal your method.

**Comment by NonVolatileHuman** [comment]
It's not about preventing someone from stealing my method, I meant using higher percentages to be able to repair higher amounts of damage to the archive.

**Comment by CarldricGaming** [comment]
https://github.com/CarldricGaming/Mini-Compressor/assets/46277745/4621b90e-9bb1-49af-92ea-8b6bfc3f49ed


Adding custom recovery percentage... almost ready to finish

**Comment by CarldricGaming** [comment]
The latest has been released. [Here](https://github.com/CarldricGaming/Mini-Compressor/releases/tag/v2023.11.12)

**Comment by CarldricGaming** [comment]
> did you try making an archive then corrupting it and attempting to recover it back?

I haven't try yet. But it would be helpful if there was something happen.
