### ISSUE TITLE
Old script Installer Creator didn't update

### ISSUE THREAD

**Issue by weednbeer** [CarldricGaming/Mini-Compressor#26]
Hello, I would like to report an issue during compilation in Installer Creator. I encountered two different errors. Firstly, the compilation completes, but when the installer starts, it indicates that the SETUP.DB file is missing. So, I created an empty SETUP.DB file from a new one, and the setup started. Then, during the installation, as I mentioned, there were two different errors. One stated that the file ENGLISH.INI was not present. I searched for these files to place them where I thought the issue might be, and I believe I found them, but not entirely sure because after recompiling, at the same point during the installation launch, there is a 7ZIPEXTRACT error. At this point, I'm not sure what to do with all these errors, and I would like to know if you know what the problem might be. Oh, and at the same time, I fixed the FRENCH.TXT file to avoid display issues with accents if you need it.

**Comment by CarldricGaming** [comment]
just patch on "Tools\InstallerCreator" folder. Thank you for your reporting.

[Compiler_IC.zip](https://github.com/CarldricGaming/Mini-Compressor/files/13328906/Compiler_IC.zip)

**Comment by weednbeer** [comment]
[French.txt](https://github.com/CarldricGaming/Mini-Compressor/files/13329219/French.txt)

here :))

**Comment by weednbeer** [comment]
Excuse me, I believe there were some mistakes. From what I've seen, it seems all corrected now.
[French.txt](https://github.com/CarldricGaming/Mini-Compressor/files/13329413/French.txt)

**Comment by weednbeer** [comment]
Here is the error that I still have when the installation starts. 
![SetupWnB tmp_0So9DyCsah](https://github.com/CarldricGaming/Mini-Compressor/assets/64708065/3933103e-7459-4c13-bd0e-1d1cf36a61c8)

**Comment by weednbeer** [comment]
![SetupWnB tmp_l3rEQ3vHSj](https://github.com/CarldricGaming/Mini-Compressor/assets/64708065/f28d4a63-f73f-4e86-aa7e-94b2e6734580)
Here is the error that I still have when the installation starts.

**Comment by CarldricGaming** [comment]
> ![SetupWnB tmp_l3rEQ3vHSj](https://user-images.githubusercontent.com/64708065/282332579-f28d4a63-f73f-4e86-aa7e-94b2e6734580.png) Here is the error that I still have when the installation starts. Failed to open 7Zip module

Which version are you using with 7zip? Also I don't quiet to see the installer that you're using with the Media (External) on the Installer Creator.

**Comment by weednbeer** [comment]
hmm 23.01 i think is the last or close... sorry for my bad english btw haha

**Comment by CarldricGaming** [comment]
[Patch_7Zip.zip](https://github.com/CarldricGaming/Mini-Compressor/files/13330983/Patch_7Zip.zip)

Patch the entire 7zip on Mini Compressor folder if it works.

**Comment by weednbeer** [comment]
"I PATCHED WITH YOUR FILE AS REQUIRED, AND SAME THING... OH, AND THANKS FOR EVERYTHING, BY THE WAY, FOR YOUR HELP! IT'S TRULY VERY MUCH APPRECIATED! IT'S NOT A BIG DEAL, DON'T STRESS ABOUT IT, JUST LET ME KNOW WHEN YOU HAVE THE TIME :))"
![SetupWnB tmp_m6GU5wrXPl](https://github.com/CarldricGaming/Mini-Compressor/assets/64708065/6d6c3ef7-35e2-4a5a-b6b3-425f74782ba0)

**Comment by CarldricGaming** [comment]
what filestream WGPTB.war for? is it accessible file or it just copy file?

**Comment by weednbeer** [comment]
"It's just a 7z archive that I give like that, and it works well with Blackbox Designer, but it's only in English and less customizable than your software... yours is just too complete and perfect. I just want to fix the little issues I have, hahaha."

**Comment by NonVolatileHuman** [comment]
Maybe the .war format isn't supported by the Mini Compressor?

**Comment by weednbeer** [comment]
Perhaps, but the .war extension is actually a 7z archive... I made a video for you! :)

https://drive.google.com/file/d/13SL8Iqoxg7FU-VEx0lcoDxX5cN4z9J1g/view?usp=drive_link

**Comment by weednbeer** [comment]
"Here's the repack I made with Blackbox... just showing you that the .row 7zip archive is supported despite the extension."
https://drive.google.com/file/d/1Di5kaHWIbZAxquzIHO1d7xRqi_FBS0Cd/view?usp=drive_link

**Comment by NonVolatileHuman** [comment]
Apparently, the 7zip package in Mini Compressor doesn't support .war extension?

**Comment by CarldricGaming** [comment]
I don't think that i didn't use any types of extension that. If the filestream was fail again, maybe you can give me some a sample of 7z.dll that has been modified on your blackbox script.

**Comment by weednbeer** [comment]
Do you want me to send you the complete script?

**Comment by NonVolatileHuman** [comment]
no, only the file called "7z.dll" in the black-box directory

**Comment by weednbeer** [comment]
ok

**Comment by weednbeer** [comment]
"I tried replacing the 7z.dll from the other one with yours without success... I suspected it, but I gave it a try, haha."

**Comment by CarldricGaming** [comment]
> "I PATCHED WITH YOUR FILE AS REQUIRED, AND SAME THING... OH, AND THANKS FOR EVERYTHING, BY THE WAY, FOR YOUR HELP! IT'S TRULY VERY MUCH APPRECIATED! IT'S NOT A BIG DEAL, DON'T STRESS ABOUT IT, JUST LET ME KNOW WHEN YOU HAVE THE TIME :))" ![SetupWnB tmp_m6GU5wrXPl](https://user-images.githubusercontent.com/64708065/282398117-6d6c3ef7-35e2-4a5a-b6b3-425f74782ba0.png)

I found the solution... Please don't do this if you make something mistakes here...

![image](https://github.com/CarldricGaming/Mini-Compressor/assets/46277745/f92ced3e-5a92-470a-8916-d8d3acc89dc5)

Do this on media (external) as "{src}\WGPTB.war"

![image](https://github.com/CarldricGaming/Mini-Compressor/assets/46277745/36e4eeaa-f25f-4b7c-8840-c4b9af896524)

And your installer will work just fine.

![image](https://github.com/CarldricGaming/Mini-Compressor/assets/46277745/573a82f3-aafd-4c3b-b57f-54909fd8f767)

**Comment by CarldricGaming** [comment]
As for your trouble, Here's the theme Windows 11

![image](https://github.com/CarldricGaming/Mini-Compressor/assets/46277745/eb4bbce5-eeaf-4181-b41e-6352b1eeee8c)

[Windows 11 Installer.zip](https://github.com/CarldricGaming/Mini-Compressor/files/13343827/Windows.11.Installer.zip)

**Comment by weednbeer** [comment]
"Oh, okay. I'm on Windows 10, haha, and wow... I thought so too. I was convinced it was some small detail in the app or script somewhere, or with DLLs as you mentioned. I thank you immensely."

**Comment by CarldricGaming** [comment]
Then the cases will be close as solved issue.

**Comment by NonVolatileHuman** [comment]
@CarldricGaming you should rename this issue to help future users of the software

**Comment by CarldricGaming** [comment]
Done.
