### ISSUE TITLE
can i use this in software

### ISSUE THREAD

**Issue by furjac** [CarldricGaming/Mini-Compressor#3]
can i compress software like with this compressor

**Comment by CarldricGaming** [comment]
It depends on how you can manage to export from registry that you want to compress software like Smart Install Maker or else.

**Comment by furjac** [comment]
yeah i understand i tried to compress photoshop in freearc it fails i tried in 7zip tab it worked perfectly

**Comment by CarldricGaming** [comment]
Compress with FreeARC, use without xprecomp. Some precompressor failed to raw something. For easy to repack, use with split option if you need.

**Comment by furjac** [comment]
i need inno setup 5 enhanced software seperately will u provide me
