### ISSUE TITLE
Inno - Compression

### ISSUE THREAD

**Issue by Koomongous** [CarldricGaming/Mini-Compressor#30]
Is there a way to change the compression settings when using Inno, or a way to use an already compressed game?

**Comment by CarldricGaming** [comment]
I believe you might be want to change or adding some stuff that some codec would suitable for you? If that case, Fileforums can answer there.

**Comment by Koomongous** [comment]
Could I get some clarification, do the settings used in FreeArc change the compression used when compiling using Inno?
![image](https://github.com/user-attachments/assets/f7efe6af-edf2-4c5c-8f5c-1e5382d18a09)

**Comment by Koomongous** [comment]
Unrelated, where could I change what font the inno installer uses?

Also, when running the compiled inno installer, I'm guessing the graphics system check is supposed to show your system VRAM? It doesn't seem to report correctly as it shows 4GB while my system has 16GB VRAM.

**Comment by CarldricGaming** [comment]
> Could I get some clarification, do the settings used in FreeArc change the compression used when compiling using Inno? ![image](https://private-user-images.githubusercontent.com/71297607/349344381-f7efe6af-edf2-4c5c-8f5c-1e5382d18a09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMjU2OTIsIm5iZiI6MTcyMTIyNTM5MiwicGF0aCI6Ii83MTI5NzYwNy8zNDkzNDQzODEtZjdlZmU2YWYtZWRmMi00YzVjLThmNWMtMWU1MzgyZDE4YTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDE0MDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1OTE3ZGY1YjZhZmY1MTAzMmUwODFkNmY2YmExZTk5Mzc0MGExNGNiZGI3ZTMyM2Y4NDU3NDkxNGVlZGY5NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zfr0LH1FP3h1RClOsbml77qzQqctU6nuvuVSlD5Z0kk) ![image](https://private-user-images.githubusercontent.com/71297607/349344526-7ca0dcdc-bc32-4ee7-a512-348c27cd611e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMjU2OTIsIm5iZiI6MTcyMTIyNTM5MiwicGF0aCI6Ii83MTI5NzYwNy8zNDkzNDQ1MjYtN2NhMGRjZGMtYmMzMi00ZWU3LWE1MTItMzQ4YzI3Y2Q2MTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDE0MDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4M2NhZGNjM2NiMGQ3YWU1NzZmNDdlYzQ2NGU0ODI0Njg2YzgzZDU3NzI5YWQ1NmY4ZTk5N2VmNTRlYjI4NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FCySwbzOmAZ2VQVCpY9C-zIDssCG_6_iPZgrYBGfsJs)

For the installer script, [here](https://fileforums.com/showthread.php?t=99073&highlight=Gupta)

also, the freearc guide would be uploaded depending if I have a free time.

**Comment by CarldricGaming** [comment]
https://github.com/CarldricGaming/Mini-Compressor/releases/download/v2024.07.08/How.to.use.7z

here's the tutorial

**Comment by Koomongous** [comment]
Thanks for the tutorial! I'll keep looking around for things I can customize & modify.
Great tool my guy :)
