### ISSUE TITLE
Inno Setup 5 Enhanced Edition needed.

### ISSUE THREAD

**Issue by CarldricGaming** [CarldricGaming/Mini-Compressor#4]
i need inno setup 5 enhanced software seperately will u provide me

_Originally posted by @furjac in https://github.com/CarldricGaming/Mini-Compressor/issues/3#issuecomment-975656890_

**Comment by CarldricGaming** [comment]
Here is the link. [https://fileforums.com/showpost.php?p=418194&postcount=16](url)

**Comment by furjac** [comment]
when i use WPI installer the desktop shortcut not coming its showing .ink file how to fix it

**Comment by CarldricGaming** [comment]
> c

which one WPI did you use right now?

**Comment by furjac** [comment]
https://fileforums.com/showpost.php?p=491935&postcount=173
from here i downloaded

**Comment by furjac** [comment]
https://fileforums.com/showpost.php?p=491935&postcount=173
from here i downloaded

**Comment by CarldricGaming** [comment]
> https://fileforums.com/showpost.php?p=491935&postcount=173 from here i downloaded

Ask **pratikpatel8982**. He's one of the guys I know that can fix it. Try dm him on Fileforums.
