### ISSUE TITLE
How to use custom methods

### ISSUE THREAD

**Issue by furjac** [CarldricGaming/Mini-Compressor#5]
oo2reck:8 or xtool:kraken:8 
bpk+xtool:mreflate+srep_new+4x4:b64mb:lzma:ultra:64m:bt4:fb273:lc8:mc1000000
how to use custom methods like this

**Comment by CarldricGaming** [comment]
> oo2reck:8 or xtool:kraken:8 bpk+xtool:mreflate+srep_new+4x4:b64mb:lzma:ultra:64m:bt4:fb273:lc8:mc1000000 how to use custom methods like this

You need to configure the arc.ini file on the Compression > FreeARC > arc.ini file. 
Also one of your method that you're try using:
> bpk+xtool:mreflate+srep_new+4x4:b64mb:lzma:ultra:64m:bt4:fb273:lc8:mc1000000
Mostly this method would be a struggle on your computer machine.
This is the way to fix it:
> xreflate+static2+Lz4X4/$bink=bink

**Comment by furjac** [comment]
ok

**Comment by CarldricGaming** [comment]
![image](https://user-images.githubusercontent.com/46277745/144882857-686b5702-8694-45d8-9fc9-c871e655d0dd.png)

Also forgot. To enable the custom method, select **[CUSTOM]** to enable it.
