### ISSUE TITLE
im getting error 

### ISSUE THREAD

**Issue by furjac** [CarldricGaming/Mini-Compressor#6]
![Screenshot (19)](https://user-images.githubusercontent.com/81816200/145948865-95ec344a-d617-4b17-8dcd-9f604966a007.png)
how to solve this

**Comment by furjac** [comment]
i tried to decompress fitgirl files how to solve any solution

**Comment by CarldricGaming** [comment]
> i tried to decompress fitgirl files how to solve any solution

When you try to decompress fitgirl files, actually you can't. Some unarc.dll wasn't same as you know it. Fitgirl use other freearc protect which you couldn't able to decompress file from fitgirl. The key from MC Freearc Protect wasn't same as the fitgirl Freearc Protect. That's a different.

**Comment by furjac** [comment]
ok i understand means i cant able to extract right

**Comment by furjac** [comment]
how to get more compression ratio then her

**Comment by furjac** [comment]
when i compress it with custom method xzlib+static2+LZ4x4 it  is showing error failed compression not done i need solution plz

**Comment by furjac** [comment]
what is the use of this highlighted plz explain
![Screenshot (23)](https://user-images.githubusercontent.com/81816200/146123506-fa92393a-409a-4299-b409-327d72a61f7c.png)

**Comment by CarldricGaming** [comment]
> how to get more compression ratio then her

See the details here
https://fileforums.com/showthread.php?t=101639

**Comment by CarldricGaming** [comment]
> when i compress it with custom method xzlib+static2+LZ4x4 it is showing error failed compression not done i need solution plz

Watch carefully on the memo 2 section, where arc process was give you error's of method. Save the result as txt and upload here.

**Comment by CarldricGaming** [comment]
> what is the use of this highlighted plz explain ![Screenshot (23)](https://user-images.githubusercontent.com/81816200/146123506-fa92393a-409a-4299-b409-327d72a61f7c.png)

Speaking of LoLZ:
F = fastest compression
N = normal compression
X = high compression
G= best compression
