### ISSUE TITLE
how to get multiple output at once like diskspanGui

### ISSUE THREAD

**Issue by furjac** [CarldricGaming/Mini-Compressor#7]
in Diskspan Gui its very easy only i need to enter the game path it divide into multiple .bin files how to do in ur software the same thing if any plz explain it plz

**Comment by furjac** [comment]
[MC_Result1.txt](https://github.com/CarldricGaming/Mini-Compressor/files/7832115/MC_Result1.txt)
this is the error plz help  solve this

**Comment by CarldricGaming** [comment]
> in Diskspan Gui its very easy only i need to enter the game path it divide into multiple .bin files how to do in ur software the same thing if any plz explain it plz

![image](https://user-images.githubusercontent.com/46277745/148637090-cfbcf57b-10f2-45d8-848e-75544d567454.png)
see the details...

**Comment by CarldricGaming** [comment]
> [MC_Result1.txt](https://github.com/CarldricGaming/Mini-Compressor/files/7832115/MC_Result1.txt) this is the error plz help solve this

I didn't see MC_Result2.txt

**Comment by furjac** [comment]
this file is emptyy nothing in it

**Comment by furjac** [comment]
and ur software is literally amazing i love this software

**Comment by CarldricGaming** [comment]
> this file is emptyy nothing in it unable to upload

in that case, nothing happen to see.
closed.

**Comment by furjac** [comment]
can i rename the compressed .bin file to any other .file

**Comment by CarldricGaming** [comment]
> can i rename the compressed .bin file to any other .file

Yes. Absolutely.
